### ISSUE TITLE
How do you add new features?

### ISSUE THREAD

**Issue by cjds** [levavakian/howm#1]
Guide on how to do dev. I tried `/.dev.sh` and `go install` but I get this on the binary

```
root@cjds-XPS-15-9570:/go/src/github.com/levavakian/rowm# /go/bin/rowm 
WINGO ERROR: xdg.go:42: Could not find a 'DejaVuSans.ttf' file. Tried the following paths: /root/.local/share/wingo/DejaVuSans.ttf, /usr/local/share/wingo/DejaVuSans.ttf, /usr/share/wingo/DejaVuSans.ttf, /usr/local/go/src/github.com/BurntSushi/wingo/data/DejaVuSans.ttf, /go/src/github.com/BurntSushi/wingo/data/DejaVuSans.ttf
root@cjds-XPS-15-9570:/go/src/github.com/levavakian/rowm# 
```

**Comment by levavakian** [comment]
use go-install.sh or docker-install.sh first and then run test.sh. xephyr itself doesnt work great in rowm yet so its better if you do this in regular gnome

**Comment by cjds** [comment]
Can I use `./dev.sh` and do `docker-install.sh` from `./dev.sh`?

**Comment by levavakian** [comment]
yes, but you run both from the host, you can't really run the window manager inside of the docker because things get weird.

**Comment by cjds** [comment]
Gotcha
